# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20170814_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='slug',
            field=models.CharField(blank=True, max_length=205),
        ),
    ]
