# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_musician_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmember',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_musicians', to='musicapp.Band'),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_member', to='musicapp.Musician'),
        ),
        migrations.AlterUniqueTogether(
            name='bandmember',
            unique_together=set([('musician', 'band')]),
        ),
    ]
