# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20170814_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='released',
            field=models.IntegerField(),
        ),
    ]
